### PR TITLE
BUG Prevent nested permissions from breaking recursive publishing

### LINKED ISSUE #112: BUG Publishing recursive records sometimes fails if canPublish() = false for a child record
To replicate:

 - Page has_one / owns a File
 - Log in as a content author with only edit pages permissions
 - Edit a page, upload a file
 - Publish the page
 - Notice "server error" message (because File::canPublish() is false without 
image

 
Solution needs discussion.

fixed with https://github.com/silverstripe/silverstripe-versioned/pull/113

Also see https://github.com/silverstripe/silverstripe-framework/issues/7837 for related discussion

### PR DESCRIPTION
**Pull request by tractorcow**
ENHANCEMENT Modify permission checks to require outside invocation instead of verifying internally (ref: https://docs.silverstripe.org/en/4/developer_guides/model/permissions/)

Fixes #112 
Fixes https://github.com/silverstripe/silverstripe-framework/issues/7837

Note: It would be good for a @silverstripe/core-team to confirm my thinking regarding the permissions (see the link above). I feel that we should stick with the convention of requiring user code to invoke those permission checks, rather than internally failing if any are denied, causing exceptions.

### CODE REVIEW

File: src/ChangeSet.php [hunk 1]
```diff
@@ -114,6 +114,8 @@ class ChangeSet extends DataObject
     /**
      * Publish this changeset, then closes it.
      *
+     * User code must call {@see canPublish()} prior to invoking this method.
```
Comment (flamerohr) [inline src/ChangeSet.php]: "should call" rather than "must call" right?
since CLI invocations could just forego permission checks

File: src/Versioned.php [hunk 2]
```diff
@@ -1487,14 +1487,13 @@ public function publishRecursive()
     /**
      * Publishes this object to Live, but doesn't publish owned objects.
      *
+     * User code must call {@see canPublish()} prior to invoking this method.
```
Comment (flamerohr) [inline src/Versioned.php]: Same comment as above

File: src/Versioned.php [hunk 3]
```diff
@@ -1587,36 +1586,29 @@ public function unlinkDisownedObjects($sourceStage, $targetStage)
     /**
      * Removes the record from both live and stage
      *
+     * User code must call {@see canArchive()} prior to invoking this method.
```
Comment (flamerohr) [inline src/Versioned.php]: Same comment above

File: src/Versioned.php [hunk 4]
```diff
@@ -1631,15 +1623,13 @@ public function deleteFromChangeSets()
     /**
      * Removes this record from the live site
      *
+     * User code must call {@see canUnpublish()} prior to invoking this method.
```
Comment (flamerohr) [inline src/Versioned.php]: Same comment as above

File: src/Versioned.php [hunk 5]
```diff
@@ -1688,15 +1678,13 @@ public function hasPublishedOwners()
     /**
      * Revert the draft changes: replace the draft content with the content on live
      *
+     * User code must call {@see canRevertToLive()} prior to invoking this method.
```
Comment (flamerohr) [inline src/Versioned.php]: Same comment as above

**Comment by flamerohr** [comment]
Overall makes sense, I needed to refer to the big red box at the bottom of the link to understand why the `canPublish` checks were removed completely - as adding the explicit filter seemed like enough at first glance.

**Comment by tractorcow** [comment]
Done @flamerohr

**Comment by flamerohr** [comment]
will this require any admin/cms/asset pull requests to re-add the `canPublish` or `canArchive` calls/checks back in?

**Comment by tractorcow** [comment]
Those should already be checking those permissions.

**Comment by tractorcow** [comment]
@kinglozzer do you mind giving this a review? I'd appreciate a third opinion please. :)
